name: MarketSage Daily Run

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 5:30 PM IST (12:00 UTC)
  workflow_dispatch:       # Allow manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MarketSage Bot
        run: |
          ls -la
          python marketsage.py
